# safelist
branches:
  only:
    - main

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: true
      language: node_js
      node_js: '12'
      addons:
        apt:
          packages:
            - libx11-dev
            - zlib1g-dev
            - libpng-dev
            - libxtst-dev

script: bash build.sh
