branches:
  only:
    - main

image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 12 x64

build_script:
  - ps: git clone https://${GH_TOKEN}github.com/syntaxltd/silgred-desktop silgred-desktop
  - ps: cd silgred-desktop
  - npm install
  - npm run dist